import { Lead } from "../data/crmData";
import {
  Overview, ConversionMetric, StageCount, HourCount, DayCount, DayOfWeek,
  CampaignMetric, CampaignFlag, CreativeMetric, AdAlert, TrackedCampaign,
} from "./analytics";
import { VipMember } from "./members";
import { AffiliatePerformance } from "./affiliates";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const MOCK_LEADS: Lead[] = [
  {
    id: "1001",
    name: "Ahmed Al Rashidi",
    username: "@ahmed_rashidi",
    stage: "Deposit Intent",
    stageEnteredAt: hoursAgo(2),
    classification: "warm_lead",
    notes: "Very interested, mentioned he wants to start small. Follow up on deposit.",
    avatar: "AA",
    lastMessageAt: hoursAgo(1),
    unread: 3,
    escalated: true,
  },
  {
    id: "1002",
    name: "Sara Khalid",
    username: "@sara_k",
    stage: "Hesitant / Ghosting",
    stageEnteredAt: hoursAgo(54),
    classification: "new_lead",
    notes: "",
    avatar: "SK",
    lastMessageAt: hoursAgo(54),
    unread: 0,
    escalated: false,
  },
  {
    id: "1003",
    name: "Mohammed Farouq",
    username: "@mfarouq99",
    stage: "Deposited",
    stageEnteredAt: daysAgo(3),
    classification: "vip",
    notes: "Deposited $500. Happy with signals so far.",
    avatar: "MF",
    lastMessageAt: hoursAgo(5),
    unread: 0,
    escalated: false,
  },
  {
    id: "1004",
    name: "Fatima Nasser",
    username: "@fatima_n",
    stage: "Link Sent",
    stageEnteredAt: hoursAgo(18),
    classification: "warm_lead",
    notes: "",
    avatar: "FN",
    lastMessageAt: hoursAgo(18),
    unread: 1,
    escalated: true,
  },
  {
    id: "1005",
    name: "Omar Bin Yusuf",
    username: "@omar_by",
    stage: "New Lead",
    stageEnteredAt: hoursAgo(1),
    classification: "new_lead",
    notes: "",
    avatar: "OB",
    lastMessageAt: hoursAgo(1),
    unread: 2,
    escalated: false,
  },
  {
    id: "1006",
    name: "Layla Hassan",
    username: "@layla_h",
    stage: "Qualified",
    stageEnteredAt: hoursAgo(8),
    classification: "warm_lead",
    notes: "Has trading experience. Interested in forex.",
    avatar: "LH",
    lastMessageAt: hoursAgo(6),
    unread: 0,
    escalated: false,
  },
  {
    id: "1007",
    name: "Khalid Mansour",
    username: "@k_mansour",
    stage: "Account Created",
    stageEnteredAt: hoursAgo(14),
    classification: "new_lead",
    notes: "",
    avatar: "KM",
    lastMessageAt: hoursAgo(14),
    unread: 1,
    escalated: false,
  },
  {
    id: "1008",
    name: "Nour Al Amin",
    username: "@nour_amin",
    stage: "VIP Member",
    stageEnteredAt: daysAgo(7),
    classification: "vip",
    notes: "Referred 2 friends. Very engaged with signals.",
    avatar: "NA",
    lastMessageAt: hoursAgo(3),
    unread: 0,
    escalated: false,
  },
  {
    id: "1009",
    name: "TradingGuru99",
    username: "@tradingguru99",
    stage: "New Lead",
    stageEnteredAt: hoursAgo(0.5),
    classification: "affiliate",
    notes: "Runs a Telegram trading channel. Potential affiliate.",
    avatar: "TG",
    lastMessageAt: hoursAgo(0.5),
    unread: 4,
    escalated: false,
  },
  {
    id: "1010",
    name: "random_user",
    username: "@random123",
    stage: "New Lead",
    stageEnteredAt: daysAgo(2),
    classification: "noise",
    notes: "",
    avatar: "RU",
    lastMessageAt: daysAgo(2),
    unread: 0,
    escalated: false,
  },
];

export const MOCK_OVERVIEW: Overview = {
  total_leads: 47,
  new_today: 5,
  new_this_week: 14,
  total_deposited: 9,
  overall_conversion: 19,
  avg_days_to_deposit: 4.2,
};

export const MOCK_CONVERSIONS: ConversionMetric[] = [
  { label: "New Lead → Qualified",        from_entries: 47, to_entries: 31, rate: 66, target: 60 },
  { label: "Qualified → Link Sent",       from_entries: 31, to_entries: 22, rate: 71, target: 65 },
  { label: "Link Sent → Account Created", from_entries: 22, to_entries: 15, rate: 68, target: 70 },
  { label: "Account Created → Deposited", from_entries: 15, to_entries:  9, rate: 60, target: 65 },
  { label: "Overall (Lead → Deposit)",    from_entries: 47, to_entries:  9, rate: 19, target: 10 },
];

export const MOCK_STAGES: StageCount[] = [
  { stage: 1, label: "New Lead",           count: 12 },
  { stage: 2, label: "Qualified",          count: 9  },
  { stage: 3, label: "Hesitant/Ghosting",  count: 7  },
  { stage: 4, label: "Link Sent",          count: 6  },
  { stage: 5, label: "Account Created",    count: 4  },
  { stage: 6, label: "Deposit Intent",     count: 3  },
  { stage: 7, label: "Deposited",          count: 5  },
  { stage: 8, label: "VIP Member",         count: 1  },
];

export const MOCK_HOURLY: HourCount[] = Array.from({ length: 24 }, (_, h) => {
  // Peaks around 10-12am and 7-9pm (Dubai time)
  const morning = Math.max(0, 8 - Math.abs(h - 11) * 2);
  const evening = Math.max(0, 6 - Math.abs(h - 20) * 2);
  const base = Math.floor(morning + evening + Math.random() * 2);
  return { hour: h, count: base };
});

export const MOCK_LEADS_OVER_TIME: DayCount[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date(now.getTime() - (29 - i) * 86400000);
  return {
    date: date.toISOString().slice(0, 10),
    count: Math.floor(Math.random() * 5 + 1),
  };
});

export const MOCK_DAY_OF_WEEK: DayOfWeek[] = [
  { day: "Mon", leads: 11, deposits: 2 },
  { day: "Tue", leads: 9,  deposits: 3 },
  { day: "Wed", leads: 8,  deposits: 1 },
  { day: "Thu", leads: 10, deposits: 2 },
  { day: "Fri", leads: 4,  deposits: 0 },
  { day: "Sat", leads: 3,  deposits: 1 },
  { day: "Sun", leads: 2,  deposits: 0 },
];

export const MOCK_CAMPAIGNS: CampaignMetric[] = [
  {
    campaign_id: "23850001",
    campaign_name: "Trading Signals — UAE Lookalike",
    spend: 1240.50,
    impressions: 84200,
    clicks: 1103,
    leads: 31,
    deposits: 7,
    cpl: 40.02,
    cpd: 177.21,
  },
  {
    campaign_id: "23850002",
    campaign_name: "Free Signals — KSA Interest",
    spend: 890.00,
    impressions: 61500,
    clicks: 742,
    leads: 19,
    deposits: 2,
    cpl: 46.84,
    cpd: 445.00,
  },
  {
    campaign_id: "23850003",
    campaign_name: "VIP Access — Retargeting",
    spend: 520.75,
    impressions: 29800,
    clicks: 489,
    leads: 14,
    deposits: 4,
    cpl: 37.20,
    cpd: 130.19,
  },
  {
    campaign_id: "23850004",
    campaign_name: "Forex Results — Egypt Broad",
    spend: 310.00,
    impressions: 45000,
    clicks: 390,
    leads: 8,
    deposits: 0,
    cpl: 38.75,
    cpd: null,
  },
];

export const MOCK_CAMPAIGN_FLAGS: CampaignFlag[] = [
  {
    campaign_id: "23850002",
    campaign_name: "Free Signals — KSA Interest",
    consecutive_days: 4,
    latest_cpd: 445.00,
  },
];

export const MOCK_CREATIVES: CreativeMetric[] = [
  {
    ad_id: "ad_001",
    ad_name: "Results Video — 3x Returns",
    campaign_id: "23850001",
    campaign_name: "Trading Signals — UAE Lookalike",
    spend: 520.00,
    impressions: 38400,
    clicks: 490,
    leads: 14,
    deposits: 4,
    cpl: 37.14,
    cpd: 130.00,
  },
  {
    ad_id: "ad_002",
    ad_name: "Testimonial — Ahmed Story",
    campaign_id: "23850001",
    campaign_name: "Trading Signals — UAE Lookalike",
    spend: 720.50,
    impressions: 45800,
    clicks: 613,
    leads: 17,
    deposits: 3,
    cpl: 42.38,
    cpd: 240.17,
  },
  {
    ad_id: "ad_003",
    ad_name: "VIP Access — Countdown",
    campaign_id: "23850003",
    campaign_name: "VIP Access — Retargeting",
    spend: 520.75,
    impressions: 29800,
    clicks: 489,
    leads: 14,
    deposits: 4,
    cpl: 37.20,
    cpd: 130.19,
  },
  {
    ad_id: "ad_004",
    ad_name: "Free Signals — Static Image",
    campaign_id: "23850002",
    campaign_name: "Free Signals — KSA Interest",
    spend: 890.00,
    impressions: 61500,
    clicks: 742,
    leads: 19,
    deposits: 2,
    cpl: 46.84,
    cpd: 445.00,
  },
  {
    ad_id: "ad_005",
    ad_name: "Forex Egypt — Carousel",
    campaign_id: "23850004",
    campaign_name: "Forex Results — Egypt Broad",
    spend: 310.00,
    impressions: 45000,
    clicks: 390,
    leads: 8,
    deposits: 0,
    cpl: 38.75,
    cpd: null,
  },
];

export const MOCK_AD_ALERTS: AdAlert[] = [
  {
    type: "cpd",
    severity: "critical",
    campaign_name: "Free Signals — KSA Interest",
    message: "CPD €445.00 exceeds threshold €150",
    value: 445.00,
    threshold: 150,
  },
  {
    type: "cpd",
    severity: "critical",
    campaign_name: "Testimonial — Ahmed Story",
    message: "CPD €240.17 exceeds threshold €150",
    value: 240.17,
    threshold: 150,
  },
  {
    type: "cpl",
    severity: "warning",
    campaign_name: "Free Signals — KSA Interest",
    message: "CPL €46.84 exceeds threshold €3",
    value: 46.84,
    threshold: 3,
  },
];

export const MOCK_TRACKED_CAMPAIGNS: TrackedCampaign[] = [
  {
    id: 1,
    source_tag: "cmp_a3f8b2c1",
    name: "Trading Signals — UAE Lookalike",
    meta_campaign_id: "23850001",
    link: "https://t.me/YourBot?start=cmp_a3f8b2c1",
    leads: 31,
    deposits: 7,
    is_active: true,
    created_at: daysAgo(14),
  },
  {
    id: 2,
    source_tag: "cmp_d9e2f4a7",
    name: "Free Signals — KSA Interest",
    meta_campaign_id: "23850002",
    link: "https://t.me/YourBot?start=cmp_d9e2f4a7",
    leads: 19,
    deposits: 2,
    is_active: true,
    created_at: daysAgo(10),
  },
  {
    id: 3,
    source_tag: "cmp_b1c3e5f8",
    name: "VIP Access — Retargeting",
    meta_campaign_id: "23850003",
    link: "https://t.me/YourBot?start=cmp_b1c3e5f8",
    leads: 14,
    deposits: 4,
    is_active: true,
    created_at: daysAgo(7),
  },
];

export const MOCK_AFFILIATES: AffiliatePerformance[] = [
  {
    id: 1,
    name: "Jason Rivera",
    username: "@jason_r",
    referral_tag: "ref_a1b2c3d4",
    referral_link: "https://t.me/YourBot?start=ref_a1b2c3d4",
    leads: 14,
    deposits: 4,
    conversion_rate: 28.6,
    lots_traded: 50,
    commission_rate: 15,
    commission_earned: 750,
    is_active: true,
    created_at: daysAgo(30),
  },
  {
    id: 2,
    name: "Yash Mehta",
    username: "@yash_m",
    referral_tag: "ref_e5f6g7h8",
    referral_link: "https://t.me/YourBot?start=ref_e5f6g7h8",
    leads: 8,
    deposits: 2,
    conversion_rate: 25.0,
    lots_traded: 22,
    commission_rate: 15,
    commission_earned: 330,
    is_active: true,
    created_at: daysAgo(21),
  },
  {
    id: 3,
    name: "Sarah Khalil",
    username: "@sarah_k",
    referral_tag: "ref_i9j0k1l2",
    referral_link: "https://t.me/YourBot?start=ref_i9j0k1l2",
    leads: 5,
    deposits: 1,
    conversion_rate: 20.0,
    lots_traded: 10,
    commission_rate: 15,
    commission_earned: 150,
    is_active: true,
    created_at: daysAgo(14),
  },
];

export const MOCK_MEMBERS: VipMember[] = [
  {
    id: "1003",
    name: "Mohammed Farouq",
    username: "@mfarouq99",
    avatar: "MF",
    stage: 7,
    activity_status: "active",
    days_inactive: 1.2,
    last_activity_at: hoursAgo(28),
    deposit_date: daysAgo(3),
    notes: "Deposited $500. Happy with signals so far.",
    classification: "vip",
  },
  {
    id: "1008",
    name: "Nour Al Amin",
    username: "@nour_amin",
    avatar: "NA",
    stage: 8,
    activity_status: "high_value",
    days_inactive: 0.8,
    last_activity_at: hoursAgo(19),
    deposit_date: daysAgo(7),
    notes: "Referred 2 friends. Very engaged with signals.",
    classification: "vip",
  },
  {
    id: "2001",
    name: "Khaled Al Hammadi",
    username: "@khaled_h",
    avatar: "KH",
    stage: 7,
    activity_status: "at_risk",
    days_inactive: 9.5,
    last_activity_at: daysAgo(10),
    deposit_date: daysAgo(18),
    notes: "",
    classification: "vip",
  },
  {
    id: "2002",
    name: "Rania Yousef",
    username: "@rania_y",
    avatar: "RY",
    stage: 7,
    activity_status: "at_risk",
    days_inactive: 11.2,
    last_activity_at: daysAgo(11),
    deposit_date: daysAgo(22),
    notes: "Was very active initially, gone quiet.",
    classification: "vip",
  },
  {
    id: "2003",
    name: "Hassan Al Blooshi",
    username: "@hassan_b",
    avatar: "HB",
    stage: 7,
    activity_status: "churned",
    days_inactive: 21.0,
    last_activity_at: daysAgo(21),
    deposit_date: daysAgo(35),
    notes: "",
    classification: "vip",
  },
  {
    id: "2004",
    name: "Mariam Khalil",
    username: "@mariam_k",
    avatar: "MK",
    stage: 7,
    activity_status: "churned",
    days_inactive: 17.4,
    last_activity_at: daysAgo(17),
    deposit_date: daysAgo(28),
    notes: "Mentioned she was traveling.",
    classification: "vip",
  },
];
